export const CANVAS_CORE_VERSION = "0.1.2-rc.0";

export type * from "./ai-contracts.js";
export * from "./commands/change-events.js";
export * from "./commands/runtime.js";
export * from "./commands/transaction.js";
export * from "./commands/types.js";
export * from "./extensions/canvas-runtime.js";
export * from "./extensions/command-registry.js";
export * from "./extensions/migration-registry.js";
export * from "./extensions/node-kind-registry.js";
export * from "./geometry.js";
export * from "./hit-test.js";
export * from "./ir-builders.js";
export * from "./ir-mutations.js";
export * from "./ir-validators.js";
export * from "./ir-walkers.js";
export * from "./serialize/pdf.js";
export * from "./serialize/svg.js";
export * from "./snap.js";
export type * from "./types.js";
export * from "./viewport.js";
